services:
  db:
    build: .
    container_name: nextway-db
    restart: always
    tty: true
    #Left is the machine port and right is the container port
    ports:
      - '${DB_PORT}:5432'
    # Get the data stored by postgres into container in the path in colon right-side and put in left-side path in the application
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    # When the user is not defined, it's created with default user: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
