export const Providers = {
	AUTH_SERVICE: 'AuthService',
	HASH_SERVICE: 'HashService',
	JWT_SERVICE: 'JwtService',
	MAIL_SERVICE: 'MailService',
	ENV_CONFIG_SERVICE: 'EnvConfigService',
	LOGGED_USER_SERVICE: 'LoggedUserService',
	LOGGED_TENANT_SERVICE: 'LoggedTenantService',
	ZIPCODE_SERVICE: 'ZipcodeService',
	HTTP_SERVICE: 'HttpService',
	CNPJ_SERVICE: 'CnpjService',
	FILE_SERVICE: 'FileService',
	PLAN_QUERY: 'PlanQuery',
	STATE_QUERY: 'StateQuery',
	CITY_QUERY: 'CityQuery',
	PLAN_PAYMENT_SERVICE: 'PlanPaymentService',
	CARD_SERVICE: 'CardService',
	MESSAGING_SERVICE: 'MessagingService',
} as const;
