export const Providers = {
	AUTH_SERVICE: 'AuthService',
	USER_REPOSITORY: 'UserRepository',
	USER_REPOSITORY_MAPPER: 'UserRepositoryMapper',
	USER_OUTPUT_MAPPER: 'UserOutputMapper',
	USER_QUERY: 'UserQuery',
	HASH_SERVICE: 'HashService',
	JWT_SERVICE: 'JwtService',
	MAIL_SERVICE: 'MailService',
	ENV_CONFIG_SERVICE: 'EnvConfigService',
	LOGGED_USER_SERVICE: 'LoggedUserService',
	ZIPCODE_SERVICE: 'ZipcodeService',
	HTTP_SERVICE: 'HttpService',
	CNPJ_SERVICE: 'CnpjService',
} as const;
