export type NodeEnv = 'production' | 'development' | 'test';

export interface EnvConfig {
	getPort(): number;
	getJwtSecret(): string;
	getJwtExpiresIn(): number;
	getRefreshTokenSecret(): string;
	getRefreshTokenExpiresIn(): number;
	getCookiesSecret(): string;
	getDbHost(): string;
	getDbPort(): number;
	getDbName(): string;
	getDbUsername(): string;
	getDbPassword(): string;
	getDbSchema(): string;
	getDbLogs(): boolean;
	getNodeEnv(): NodeEnv;
	getMigrationRun(): boolean;
	getBaseUrl(): string;
	getJwtActiveAccountSecret(): string;
	getJwtActiveAccountExpiresIn(): number;
	getEncryptionSalts(): number;
	getApplicationMailUser(): string;
	getApplicationMailPassword(): string;
	getOrigin(): string;
	getAllowedMethods(): string;
	getRecoverUserPasswordTokenSecret(): string;
	getRecoverUserPasswordTokenExpiresIn(): number;
	getClientBaseUrl(): string;
	getZipcodeApiBaseUrl(): string;
	getCnpjApiBaseUrl(): string;
	getStorageUrl(): string;
	getStorageApiKey(): string;
	getPaymentAccessToken(): string;
	getPaymentTestPayerEmail(): string;
	getMessagingBrokerUrls(): string[];
	getMessagingBrokerQueueName(): string;
	getPaymentSecretSignature(): string;
	getPaymentRedirectUrl(): string;
}
